### PR TITLE
Add shot.now.sh, mess.now.sh, md.now.sh

### PR DESCRIPTION
**Pull request by amio**
https://shot.now.sh
https://mess.now.sh
https://md.now.sh

### CODE REVIEW

**Comment by leo** [comment]
👌 Thanks a lot!

**Comment by timneutkens** [comment]
@amio you make the most wonderful microservices 😄

**Comment by amio** [comment]
Such an enjoyment to code with now, next, micro, you guys are awesome!

**Comment by timneutkens** [comment]
👌

**Pull request merged**
